### ISSUE TITLE
Center-aligned text not working in Outlook?

### ISSUE THREAD

**Issue by JasperTey** [mailgun/transactional-email-templates#11]
In Outlook 2007, the `billing.html` template (inlined version) ends up with left-aligned text (instead of centered).

See screenshot below:

![image](https://cloud.githubusercontent.com/assets/1280844/7140811/79414f32-e29b-11e4-8e1d-e47fa4535cf0.png)

**Comment by leemunroe** [comment]
@JasperTey Thanks. Needed center alignment applied to table cells.
