### ISSUE TITLE
"See the test results" link in README gives 404

### ISSUE THREAD

**Issue by jab** [mailgun/transactional-email-templates#19]
quoting https://github.com/mailgun/transactional-email-templates/blob/master/README.md#tested-and-verified:

> We’ve tested these email templates across all the major desktop, web and mobile clients, using Litmus. [See the test results](https://litmus.com/pub/3a573b5/screenshots).

That link is currently giving 404.

**Comment by leemunroe** [comment]
@jab Thanks. Updated with new test results.
