### ISSUE TITLE
Email template not responsive, take a look at screenshot, it's email at my phone

### ISSUE THREAD

**Issue by khlystov** [mailgun/transactional-email-templates#3]
![emailtemplate](https://cloud.githubusercontent.com/assets/1534096/4644415/c80e8eec-545a-11e4-8b52-367a7fb0db0b.jpg)

**Comment by leemunroe** [comment]
@khlystov Did you happen to find a solution for Gmail on Android?

**Comment by leemunroe** [comment]
Closing to clean up. Couldn't reproduce.
