### ISSUE TITLE
Helvetica occurs twice in CSS reset

### ISSUE THREAD

**Issue by siliconforks** [mailgun/transactional-email-templates#7]
Near the top of `styles.css` there is this line:

    font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;

Is there a reason that Helvetica occurs twice (once with quotes and once without)?

**Comment by leemunroe** [comment]
No reason. My mistake.

**Comment by ro78** [comment]
It's also in inlined templates, like:
<table class="body-wrap" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background: #f6f6f6; margin: 0; padding: 0;">
