### ISSUE TITLE
Double font in inlined templates

### ISSUE THREAD

**Issue by ro78** [mailgun/transactional-email-templates#8]
Hello,

In inlined templates, the font "Helvetica" is used twice in all tags.

Examples:
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, ...
or
<body style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, ...

Romain

**Comment by leemunroe** [comment]
Thanks for pointing out. Fixed.
