### ISSUE TITLE
CSS Compiling with variables

### ISSUE THREAD

**Issue by dmyers** [mailgun/transactional-email-templates#9]
Do you have any plans or thoughts on using some kind of css compiler such as Less?

I really like this project and I think this could really be expanded on some sort of bootstrap for email type thing where you could customize colors with variables and even have mixins.

There could also be examples with images and all sorts because email is a real pain for many startups especially on the whole email client rendering front which this solves too.

With variables it could even use some of the naming that bootstrap uses so if you use bootstrap you could import that one instead possibly or use it to override so you have consistency between the two.

**Comment by leemunroe** [comment]
Thanks @dmyers glad you like these. Love your ideas. 

You might find this [Grunt workflow](https://github.com/leemunroe/grunt-email-design) useful, that includes original SCSS files. I used a version of this to create the transactional templates.

@jaegerpicker also [added Less support](https://github.com/jaegerpicker/grunt-email-design).
